### ISSUE TITLE
[Backend] Dodanie strony logowania

### ISSUE THREAD

**Issue by jwieckow** [code-bazar/project-coordinator#6]
- Strona logowania powinna być dostępna pod adresem /login
- Logowanie powinno być wykonywane przy wsparciu Spring Security
- Należy dodać do repozytorium użytkowników zamockowanych użytkowników
- Frontend powinien być zabezpieczony za pomocą csrf-token
- hasła powinny być zaszyfrowane (np blowfish)
- Po zalogowaniu do ftontu powinien zostać zwrócony kod 200, natomiast w przypadku błędnego logowania 401 (unauthorize)

https://spring.io/guides/tutorials/spring-security-and-angular-js/

**Comment by bwieckow** [comment]
Przeniesione do projektu coordinator
